### ISSUE TITLE
Conflict issue caused by channels and channels-redis versions

### ISSUE THREAD

**Issue by Vino2530** [django/channels_redis#302]
The conflict is caused by:
           The user requested channels==3.0.1
           channels-redis 2.4.2 depends on channels~=2.2

if i downgrade the channels version to 2.2, then facing this issues "AttributeError: type object 'ChatConsumer' has no attribute 'as_asgi()". 
Currently working on chat application. Locally working fine with channels==3.0.1 and channels-redis==2.4.2. But when trying to deploy to heroku server facing this issue

**Comment by carltongibson** [comment]
I think you just need to update: 

```
$ mktmpenv
$ pip install channels channels_redis
$ pip list
Package           Version
----------------- -------
...
channels          3.0.4
channels-redis    3.4.0
...
```
