### PR TITLE
Fix docs for "hosts"

### LINKED ISSUE #334: AttributeError: 'tuple' object has no attribute 'decode' when configuring using tuples
Config

```
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.pubsub.RedisPubSubChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}
```

Error:

```


  File "[..]lib/python3.10/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "[..]lib/python3.10/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "[..]lib/python3.10/site-packages/channels/sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "[..]lib/python3.10/site-packages/channels/auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "[..]lib/python3.10/site-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "[..]lib/python3.10/site-packages/channels/routing.py", line 150, in __call__
    return await application(
  File "[..]lib/python3.10/site-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "[..]lib/python3.10/site-packages/channels/consumer.py", line 46, in __call__
    self.channel_name = await self.channel_layer.new_channel()
  File "[..]lib/python3.10/site-packages/channels_redis/pubsub.py", line 34, in _async_proxy
    return await getattr(layer, name)(*args, **kwargs)
  File "[..]lib/python3.10/site-packages/channels_redis/pubsub.py", line 165, in new_channel
    await self._subscribe_to_channel(channel)
  File "[..]lib/python3.10/site-packages/channels_redis/pubsub.py", line 144, in _subscribe_to_channel
    await shard.subscribe(channel)
  File "[..]lib/python3.10/site-packages/channels_redis/pubsub.py", line 282, in subscribe
    self._ensure_redis()
  File "[..]lib/python3.10/site-packages/channels_redis/pubsub.py", line 349, in _ensure_redis
    pool = aioredis.ConnectionPool.from_url(self.host["address"])
  File "[..]lib/python3.10/site-packages/redis/asyncio/connection.py", line 1400, in from_url
    url_options = parse_url(url)
  File "[..]lib/python3.10/site-packages/redis/asyncio/connection.py", line 1292, in parse_url
    parsed: ParseResult = urlparse(url)
  File "/usr/lib/python3.10/urllib/parse.py", line 392, in urlparse
    url, scheme, _coerce_result = _coerce_args(url, scheme)
  File "/usr/lib/python3.10/urllib/parse.py", line 128, in _coerce_args
    return _decode_args(args) + (_encode_result,)
  File "/usr/lib/python3.10/urllib/parse.py", line 112, in _decode_args
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
  File "/usr/lib/python3.10/urllib/parse.py", line 112, in <genexpr>
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
AttributeError: 'tuple' object has no attribute 'decode'
```

Offending commit (presumably): 65a05285d512e32607829b45cba5b4093e6003a6

### PR DESCRIPTION
**Pull request by vanschelven**
Fixes #334 

A more thorough (and backward compatible) fix would be to actually make tuples work again.

### CODE REVIEW

**Review by sevdog — CHANGES_REQUESTED** [review]
Tuple "decoding" is not working only in `RedisPubSubChannelLayer`, the base `RedisChannelLayer` has a dedicated method to handle it:

https://github.com/django/channels_redis/blob/a7094c58a15cbf6e621b2129253060fc80cfdfad/channels_redis/core.py#L146-L169


The right way to address #334 would be to move that method out from `RedisChannelLayer` to utils module and to use it for both layers.

Anyway the docs for `RedisChannelLayer` should not be changed.

**Comment by carltongibson** [comment]
Resolved in https://github.com/django/channels_redis/pull/352
